/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.kroky.betting.gui.forms;

import java.awt.Component;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import org.apache.log4j.Logger;
import org.kroky.betting.common.enums.ProviderType;
import org.kroky.betting.common.util.Utils;
import org.kroky.betting.db.DAO;
import org.kroky.betting.db.objects.Provider;
import org.kroky.betting.db.objects.Team;
import org.kroky.betting.gui.custom.EscapableDialog;
import org.kroky.betting.gui.custom.SortedComboBoxModel;

/**
 *
 * @author Kroky
 */
public class FixturesProviderSelectionDialog extends EscapableDialog {
    /**
     * Creates new form FixturesProviderSelectionDialog
     */
    public FixturesProviderSelectionDialog(java.awt.Frame owner, Team team) {
        super(owner, true);
        initComponents();
        this.team = team;
        this.owner = owner;
        initData();
    }
    
    public FixturesProviderSelectionDialog(Dialog owner, Team team) {
        super(owner, true);
        initComponents();
        this.team = team;
        this.owner = owner;
        initData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        cbExistingProviders = new javax.swing.JComboBox();
        btnNewFixturesProvider = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnNewFixturesProvider.setText("New...");
        btnNewFixturesProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFixturesProviderActionPerformed(evt);
            }
        });

        jLabel6.setText("Please choose a fixtures provider or create a new one");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbExistingProviders, 0, 422, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewFixturesProvider))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnNewFixturesProvider, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExistingProviders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewFixturesProvider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewFixturesProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFixturesProviderActionPerformed
        NewProviderDialog d = new NewProviderDialog(this, true, ProviderType.FIXTURES, team);
        d.setVisible(true);
        final Provider p = d.getProvider();
        if(p != null) {
            cbExistingProviders.insertItemAt(p, 0);
            cbExistingProviders.setSelectedItem(p);
            btnOkActionPerformed(evt);
        }
    }//GEN-LAST:event_btnNewFixturesProviderActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        provider = (Provider) cbExistingProviders.getSelectedItem();
        closeWindow();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        closeWindow();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNewFixturesProvider;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cbExistingProviders;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private final Team team;
    private Component owner;
    private Provider provider = null;
    private static final Logger LOG = Logger.getLogger(FixturesProviderSelectionDialog.class);
    
    public Provider getProvider() {
        return provider;
    }

    private void initData() {
        List<Provider> list = new ArrayList<Provider>();
        list.addAll(DAO.getFixtureProviders(team));
        cbExistingProviders.setModel(new SortedComboBoxModel(list.toArray(new Provider[list.size()])));
        if (team.getFixturesProvider() != null) {
            cbExistingProviders.setSelectedItem(team.getFixturesProvider());
        }
        pack();
        Utils.centerOnParent(owner, this);
    }
}
